name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.16.1]  # You might need to adjust the Node.js version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      - name: path
        run: pwd
      - name: list
        run: ls
      - name: Run tests
        run: npm test -- --detectOpenHandles
        
      - name: Install PM2
        run: npm install -g pm2

      - name: Restart PM2 process
        run:  npm start        
  
